#!/usr/bin/env bash
alias ll='ls -la'

# Easier navigation: .., ..., ~
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"

alias f='open .'
alias c='/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code .'
alias n='nova .'

# Updates literally everything.
alias update='update-everything.sh'

# IP addresses.
# https://unix.stackexchange.com/a/81699/37512
alias ip="dig @resolver4.opendns.com myip.opendns.com +short"
alias ip6="dig @resolver1.ipv6-sandbox.opendns.com AAAA myip.opendns.com +short -6"
alias iplocal="ipconfig getifaddr en0"

# Copies SSH public key to pasteboard.
alias pubkey='more ~/.ssh/id_rsa.pub | pbcopy | printf "✓ Public SSH key copied to pasteboard.\n"'

# Copies GPG public key to pasteboard.
alias gpgpubkey='gpg --export --armor $GPG_KEY_ID | pbcopy | printf "✓ Public GPG key copied to pasteboard.\n"'

# Recursively deletes `.DS_Store` files.
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Empties the Trash on all mounted volumes and the main HDD.
# Also, clears Apple’s System Logs to improve shell's startup speed.
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Shows/hides hidden files in Finder.
alias show="defaults write com.apple.Finder AppleShowAllFiles -bool TRUE && killall Finder"
alias hide="defaults write com.apple.Finder AppleShowAllFiles -bool FALSE && killall Finder"

# When there's need for nyaning around - because those moments do exist, guys. Let's drop off our masks.
alias nyan="telnet nyancat.dakko.us"

# Virus scan with ClamAV.
alias virusscan="clamscan -r --bell -i /"

# Docker & Docker Compose.
alias dc="docker-compose"
